language: node_js
node_js:
  - "7"
services:
  - mysql
env:
  - TEST_DIR=API DB_HOST=127.0.0.1 DB_NAME=bionexo DB_USER=root DB_PASS=

before_install: cd $TEST_DIR && bash ./prepare_for_test.sh

install: npm install

before_script: ls && npm run build

script: npm run test