version: '3'
services:
  db:
    build: ./db
    ports:
      - '3306:3306'
    environment: 
      MYSQL_DATABASE: bionexo
      MYSQL_ROOT_PASSWORD: bionexopass
      MYSQL_USER: bionexo
      MYSQL_PASS: bionexopass

  api:
    depends_on:
      - db
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    links:
      - db

  client:
    depends_on:
      - api
    build: ./frontend
    ports:
      - "8000:3000"
    volumes:
      - ./frontend:/code
    links:
      - api
