version: '3'
services:
  api:
    depends_on:
      - db
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
  
  db:
    build: ./db
    ports:
      - '3306:3306'
    environment: 
      MYSQL_DATABASE: bionexo
      MYSQL_ROOT_PASSWORD: bionexopass
      MYSQL_USER: bionexo
      MYSQL_PASS: bionexopass
